export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const GET_PROFILES = "GET_PROFILES";
export const CLEAR_PROFILES = "CLEAR_PROFILES";
export const PROFILES_ERROR = "PROFILES_ERROR";

export const REJECTED_TICKS = "REJECTED_TICKS";
export const AWAITING_TICKS = "AWAITING_TICKS";
export const SUCCESS_TICKS = "SUCCESS_TICKS";
export const UPDATE_REJECTED_TICKS = "UPDATE_REJECTED_TICKS";
export const UPDATE_AWAITING_TICKS = "UPDATE_AWAITING_TICKS";
export const UPDATE_SUCCESS_TICKS = "UPDATE_SUCCESS_TICKS";

export const UPDATE_REJECTED_TOHLC = "UPDATE_REJECTED_TOHLC";
export const UPDATE_AWAITING_TOHLC = "UPDATE_AWAITING_TOHLC";
export const UPDATE_SUCCESS_TOHLC = "UPDATE_SUCCESS_TOHLC";

export const GET_BINARY_BALANCE = "GET_BINARY_BALANCE";
export const WAIT_BINARY_BALANCE = "WAIT_BINARY_BALANCE";

export const GET_BINARY_RUNNING_TRADES = "GET_BINARY_RUNNING_TRADES";

export const MAKE_BUY_ORDER = "MAKE_BUY_ORDER";
export const MAKE_SELL_ORDER = "MAKE_SELL_ORDER";
